[project]
name = "ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dlt[parquet,postgres]>=1.2.0",
    "duckdb>=1.1.1",
    "pandas>=2.2.3",
]
